---
title: Welcome to Homework 2
date: last-modified
author: (Ben Fenuku)
format:
    gfm:
        mermaid-format: png
---

This is my solution to homework 2. I'm using Quarto render this document from a QMD file to a regular
MD file for display on GITHUB.

## Scenario

Imagine you're designing a Library Management System for a small local library. The system needs to track information about books and library members. Each book has a unique ISBN (International Standard Book Number), a title, and a publication year. Each library member is identified by a unique member ID, and the system needs to store their name and contact information. Library members can check out books, but they don’t have to.

## Design Task 1

Identify and document the entities, attributes, and relationships using Chen notation.

```{dot}
graph ER {
    layout=neato;
  scale=1.3;
    node [shape=box]; book, member;
    node [shape=ellipse]; isbn, title, pub_year, member_id, name, contact_info  
    node [shape=diamond,style=filled,color=lightgrey]; has
    
    
    book -- has[label="1",len=1.00]
    has -- member[label="n",len=1.00]
    
    book -- isbn
    book -- title
    book -- pub_year
 
    member -- member_id
    member -- contact_info
    member -- name
    
}
```

## Design Task 2

Identify and document the entities, attributes, and relationships using Crow’s Foot notation.

<center>

::: {.column}
```{mermaid}
erDiagram
    Member ||--|{ Book : can_checkout
    Member {
        string Name
        string Member_ID
        string Contact_Info
    }
    Book{
        string ISBN
        string Title
        string pub_year
    }
```
:::

